# Generated by Django 2.0.7 on 2018-07-24 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.TextField(blank=True, max_length=14),
        ),
    ]
